### ISSUE TITLE
KeyError: 'st.session_state has no key "selected_model". Did you forget to initialize it?

### ISSUE THREAD

**Issue by billkoul** [kspviswa/local-packet-whisperer#11]
I keep getting the same error, no matter the machine i'm using. Do you have any advice?

Full error below:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/linux/.venv/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
  File "/home/linux/.venv/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 590, in code_to_exec
    exec(code, module.__dict__)
  File "/home/linux/local-packet-whisperer/bin/lpw_main.py", line 8, in <module>
    pg.run()
  File "/home/linux/.venv/lib/python3.10/site-packages/streamlit/navigation/page.py", line 291, in run
    exec(code, module.__dict__)
  File "/home/linux/local-packet-whisperer/bin/lpw_home.py", line 75, in <module>
    st.metric("Selected Model ✅", st.session_state['selected_model'])
  File "/home/linux/.venv/lib/python3.10/site-packages/streamlit/runtime/state/session_state_proxy.py", line 100, in __getitem__
    return get_session_state()[key]
  File "/home/linux/.venv/lib/python3.10/site-packages/streamlit/runtime/state/safe_session_state.py", line 94, in __getitem__
    return self._state[key]
  File "/home/linux/.venv/lib/python3.10/site-packages/streamlit/runtime/state/session_state.py", line 412, in __getitem__
    raise KeyError(_missing_key_error_message(key))
KeyError: 'st.session_state has no key "selected_model". Did you forget to initialize it? More info: https://docs.streamlit.io/develop/concepts/architecture/session-state#initialization'

**Comment by kspviswa** [comment]
Hi,
Thanks for reporting. Please upgrade lpw to 0.2.4

```
pip install -U lpw
```
